server:
  port: 28703
spring:
  application:
    name: testServer
  redis:
    host: 127.0.0.1
    #Redis服务器连接端口
    port: 6379
    #Redis服务器连接密码（默认为空）
    password:
    lettuce:
      # 关闭超时时间
      shutdown-timeout: 100
      pool:
        #连接池中的最大空闲连接
        max-idle: 15
        #连接池中的最小空闲连接
        min-idle: 0
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 15
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 1000
    #连接超时时间（毫秒）
    timeout: 100000
#跨域配置
cors:
  #是否允许跨域请求
  AllowCors: true
  #允许跨域请求白名单,只有在AllowCors值为true的时候该配置生效
  AllowedOrigins: http://localhost:28720