<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>servers</artifactId>
        <groupId>easyProject.servers</groupId>
        <version>1.0-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>testServer</artifactId>

    <properties>
        <hutool.version>5.8.10</hutool.version>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <druid-spring-boot-starter.version>1.2.8</druid-spring-boot-starter.version>
        <jsqlparser.version>3.0</jsqlparser.version>
        <dom4j.version>2.1.3</dom4j.version>
<!--        <springdoc-openapi.version>2.5.0</springdoc-openapi.version>-->
<!--        原版本不生效，spring版本是2.3.2.RELEASE，需要版本是1.x.x才能支持，否则不兼容-->
<!--        <springdoc-openapi.version>1.6.1</springdoc-openapi.version>-->
    </properties>
    <dependencies>

        <dependency>
            <groupId>cn.ecasoft</groupId>
            <artifactId>ecacore</artifactId>
            <version>1.0.211117</version>
        </dependency>
        <dependency>
            <groupId>cn.ecasoft</groupId>
            <artifactId>ecamodel</artifactId>
            <version>1.0.211117</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <!--        redis数据库交互工具-->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis</artifactId>
        </dependency>
        <!--        commons-pool12库，spring-boot-starter-data-redis的依赖默认包含了对lettuce-core的依赖，而lettuce-core使用了Apache Commons Pool库-->
        <!--        <dependency>-->
        <!--            <groupId>org.apache.commons</groupId>-->
        <!--            <artifactId>commons-pool2</artifactId>-->
        <!--        </dependency>-->
        <!--        是 Apache 提供的一个开源库，主要用于提供各种编码和解码的工具方法。它广泛应用于需要处理字符编码、数据加密、哈希算法等场景。-->
        <dependency>
            <groupId>commons-codec</groupId>
            <artifactId>commons-codec</artifactId>
        </dependency>
        <!--        cglib动态代理-->
        <dependency>
            <groupId>cglib</groupId>
            <artifactId>cglib</artifactId>
            <version>3.2.5</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
<!--        此驱动依赖必须有，没有的话启动报错缺少驱动-->
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
        </dependency>
        <dependency>
            <groupId>com.auth0</groupId>
            <artifactId>java-jwt</artifactId>
            <version>4.4.0</version>
        </dependency>
        <!--        加密与安全认证，JWT签名，浙里建使用示例使用-->
        <dependency>
            <groupId>io.jsonwebtoken</groupId>
            <artifactId>jjwt</artifactId>
            <version>0.9.0</version>
        </dependency>
        <!-- 请求参数校验相关 -->

        <dependency>
            <groupId>org.hibernate.validator</groupId>
            <artifactId>hibernate-validator</artifactId>
        </dependency>
        <!--        生成api文档
        1.自动生成 API 文档 SpringDoc OpenAPI 会根据 Spring Boot 项目中的控制器（@RestController）、请求映射（@RequestMapping）、参数（@RequestParam、@PathVariable 等）和模型（@Schema 等注解）自动生成 OpenAPI 3.0 规范的 API 文档。
        2.提供 Swagger UI 可以通过访问 http://localhost:8080/swagger-ui.html 来查看和测试 API 文档
        3. 支持 OpenAPI 3.0
        4. 与 Spring Boot 无缝集成
        5.可以通过配置文件（如 application.yml 或 application.properties）或代码自定义 API 文档的生成规则。
        -->
<!--        <dependency>-->
<!--            <groupId>org.springdoc</groupId>-->
<!--            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>-->
<!--            <version>${springdoc-openapi.version}</version>-->
<!--        </dependency>-->
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>com.spotify</groupId>
                <artifactId>docker-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
        <!--        <resources>-->
        <!--            <resource>-->
        <!--                <directory>src/main/resources</directory>-->
        <!--                <includes>-->
        <!--                    <include>**/template/**</include>-->
        <!--                </includes>-->
        <!--                <filtering>true</filtering>-->
        <!--            </resource>-->
        <!--        </resources>-->
    </build>
</project>