eca:
  data-sources:
    - guid: 12345678-0000-467d-8611-473195a02fcc
      name: easyproject
      username: root
      password: ZGiPB4Kc6K4=
      url: jdbc:mysql://127.0.0.1:3306/eca_mysql?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
      druid:
        initialSize: 10   # 初始化连接大小 默认0
        maxActive: 100   # 最大连接数 默认8
        minIdle: 5   # 最小空闲连接数 默认0
        maxWait: 5000 #获取连接时最大等待时间，单位毫秒
        validationQueryTimeout: 1
        timeBetweenEvictionRunsMillis: 60000 #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        minEvictableIdleTimeMillis: 30000 #配置一个连接在池中最小生存的时间，单位是毫秒
        # max-evictable-idle-time-millis: 300000
        testWhileIdle: true #申请连接的时候检测，建议配置为true，不影响性能，并且保证安全性
        testOnReturn: false #获取连接时执行检测，建议关闭，影响性能
        # validationQuery: SELECT 1
        connectProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000 # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        useGlobalDataSourceStat: true # 合并多个DruidDataSource的监控数据
        maxPoolPreparedStatementPerConnectionSize: -1  # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
        removeAbandoned: true  # 超过时间限制是否回收
        removeAbandonedTimeout: 180  # 超时时间；单位为秒。180秒=3分钟
        logAbandoned: true # 关闭abanded连接时输出错误日志
        keepAlive: false
        # xlk add
        remove-abandoned: true
        remove-abandoned-timeout: 180
        log-abandoned: true
        filters: mergeStat  # 配置监控统计拦截的filters， 去掉后监控界面sql将无法统计，wall 用于防火墙
        use-global-data-source-stat: true